name: Post coverage comment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  test:
    name: Publish coverage Comment
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      actions: read
      pull-requests: write
      contents: write
    steps:
      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@a11ba0d113cc7e831a6f39182ae02b244c1c23d8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
